name: craftalism_market
version: '1.0-SNAPSHOT'
main: io.github.HenriqueMichelini.craftalism_market.CraftalismMarket
api-version: '1.21'
commands:
  market:
    description: Opens the inventory viewer GUI.
    usage: /market.
    permission: craftalismmarket.market.use
    permission-message: You do not have permission to use this command.
